title: Allen Huang
position: PhD in Individualized Interdisciplinary Program (Financial Technology)
description: Allen Huang is a researcher working on quantitative finance, machine learning, financial networks, and agentic AI.
canonical: https://allenh16.github.io/
github_link: https://github.com/allenh16
favicon: ./assets/img/kl.png
favicon_dark: ./assets/img/kl.png
enable_footnote: false
auto_dark_mode: true
font: "Sans Serif"
remote_theme: yaoyao-liu/minimal-light
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
